sqlx: 0.6 -> 0.7
casbin-rs/sqlx-adapter pull request #80
Opened 2023-07-04 17:19 UTC by ip1981

2023-07-04 17:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin-rs/sqlx-adapter?pullRequest=80) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin-rs/sqlx-adapter?pullRequest=80) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin-rs/sqlx-adapter?pullRequest=80) it.</sub>

2023-07-05 06:58 UTC, hsluoyz requested changes

2023-07-05 06:58 UTC, hsluoyz commented on .sqlx/query-1cabd2f674da323da9e0da724d3bcfe5f968b31500e8c8cf97fe16814bc04164.json
> +{
Remove the `.sqlx` folder

2023-07-05 06:58 UTC, hsluoyz commented on sqlx-data.json
> -{
Why remove it?

2023-07-05 06:59 UTC, hsluoyz commented
@ip1981 fix all errors:

![image](https://github.com/casbin-rs/sqlx-adapter/assets/3787410/f6640fae-a653-4fdd-acd8-a5ecb7e19377)

2023-07-05 09:41 UTC, ip1981 commented on sqlx-data.json
> -{
Please read sqlx changelog )

2023-07-05 09:42 UTC, ip1981 commented
There are no errors I can fix )

2023-11-28 03:41 UTC, hsluoyz commented
@ip1981 plz fix: https://github.com/casbin-rs/sqlx-adapter/actions/runs/7013819881/job/19080557423?pr=80

![image](https://github.com/casbin-rs/sqlx-adapter/assets/3787410/7136341b-ef83-4526-8260-eca9337e51cc)

2024-02-08 17:23 UTC, hsluoyz commented
Replaced by: https://github.com/casbin-rs/sqlx-adapter/pull/87

2024-02-08 17:23 UTC, closed without merging